### ISSUE TITLE
URLs with domain names longer than 4 characters are not autolinked

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#69]
Attempted to fix in #68, but using [brevity](https://github.com/kylewm/brevity) was suggested instead.

For example, http://lancey.space would not be parsed as a link

**Comment by kylewm** [comment]
Finally fixed in https://github.com/kylewm/redwind/commit/c4531eec3394ccde69371b3468da38abf21dd8e3

Confirmed here https://kylewm.com/2015/09/red-wind-can-now-autolink-fancy-domains-like-lancey

Note this requires a new version of brevity (>=0.2.0) ... I modified the library itself to do some autolinking. Let me know if you notice any problems!
